# Generated by Django 2.1.2 on 2018-10-21 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urpScrapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(default='', max_length=255)),
                ('attendClassTeacher', models.CharField(default='', max_length=255)),
                ('classroomName', models.CharField(default='', max_length=255)),
                ('weekDescription', models.CharField(default='', max_length=255)),
                ('classDay', models.CharField(default='', max_length=255)),
                ('classSessions', models.CharField(default='', max_length=255)),
                ('continuingSession', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'classschedule',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(default='', max_length=255, unique=True)),
                ('userName', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='urpscrapy',
            name='userID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='warehouse.user', to_field='userID'),
        ),
    ]
