# Generated by Django 2.1.2 on 2018-10-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urpScrapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(default='', max_length=255)),
                ('attendClassTeacher', models.CharField(default='', max_length=255)),
                ('classroomName', models.CharField(default='', max_length=255)),
                ('weekDescription', models.CharField(default='', max_length=255)),
                ('classDay', models.CharField(default='', max_length=255)),
                ('classSessions', models.CharField(default='', max_length=255)),
                ('continuingSession', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'classschedule',
            },
        ),
    ]
