# Generated by Django 2.1.2 on 2018-10-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userPassword',
            field=models.CharField(default='', max_length=255),
        ),
    ]
